### ISSUE TITLE
Kurdish translation not support by default font used in LS

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backlog#65]
**Describe the bug**
Kurdish characters are not displayed correctly in the questionnaire. The issue seems to be due to the font used in the LS template as in the quick translations they appear correctly. 

Example questionnaire with Kurdish translations:
https://ls.herams.org/admin/survey/sa/view/surveyid/586577

**Expected Behaviour**
If the issue is indeed the LS template, can we create a new template that either supports English, Arabic and Kurdish or have different fonts depending on the user-selected language? 

**Screenshots**
![image](https://user-images.githubusercontent.com/18245059/212560328-49267244-acc2-4fd0-aabf-b8dd0ddc70f3.png)

**Comment by luna404** [comment]
Proposed font supporting Kurdish characters proposed by the country office: **Ali Alkwnd**

**Comment by SamMousa** [comment]
Hmm, this will be hard to identify for anyone not familiar with these characters.
We should use 1 font that supports all languages. That'd be a simple change in the LS template.

**Comment by SamMousa** [comment]
Please select a font from: https://fonts.google.com/ 
That works with all required languages.

**Comment by luna404** [comment]
Finding a font that supports English, Arabic and Kurdish seem to be rather challenging. It appears that even fonts that claim to support Kurdish characters defacto do not do this. 
So far the only font we know that correctly supports Kurdish is the Ali Alkwnd font but it doesn't support Arabic.

**Comment by SamMousa** [comment]
> Btw, I asked about the licensing and they assured me that we can use it without requiring a license.

Feels legit :D I'll fix it.

**Comment by SamMousa** [comment]
@luna404 I've fixed it for now, for testing made all the text red and bold (so you know that the custom font is applied). If you find any non-red text report it.

When you're satisfied it works please let me know and i'll remove the red color and  boldness.

**Comment by luna404** [comment]
Is it possible that it's not displaying the new font? They tested it but their feedback is, it's still wrong and the font doesn't look like the one they've shared.

**Comment by luna404** [comment]
Feedback from the country: It's not perfect, apparently even their font is not reflecting all characters correctly, but it's good enough that we consider the issue resolved. 
Thanks a lot!

**Comment by luna404** [comment]
Looks like it's still an issue after all. Is it possible that something overwrites the default Kurdish font? 

First line is what we display on the platform, the second line is the same phrase using the same Kurdish font in word.

 
![MicrosoftTeams-image (7)](https://user-images.githubusercontent.com/18245059/215986225-f195ef51-b214-4900-b4f6-9870ece55212.png)

**Comment by SamMousa** [comment]
What question is this?

**Comment by luna404** [comment]
Here's the word document from them [kurdish.docx](https://github.com/HeRAMS-WHO/herams-backlog/files/10673813/kurdish.docx)

**Comment by SamMousa** [comment]
Honestly what I think is happening is that they are just making typos in their language.
When looking into other kurdish fonts I see the same issue; I see the symbol i'm looking for but applying it to the word doesn't show the one I'm looking for. Copying it from the website I see the symbol in Word correctly which means they have typed in the wrong symbol.


![image](https://user-images.githubusercontent.com/547021/217230222-7ed31f71-c827-43ce-bbad-6ca03498d0fb.png)

These are 2 different symbols in the same font (Ali_K_Alwand) on my system.
I don't know how to type any of these so can't verify for other symbols.

**Comment by SamMousa** [comment]
Can you send me his contact inf in a private channel (signal / mail)? I'll try to set up a meeting to see what we can do.

**Comment by luna404** [comment]
I've spoken to the FP in the country and they'd prefer if we can put the issue on hold for now. They have trained everyone in Arabic now and will go ahead with the Arabic version of the questionnaire.
